### PR TITLE
moved requires outside of function so Jest tests work

### PR DESCRIPTION
**Pull request by sk3tch**
Hi!
We've been having trouble with the Jest tests for our app and after troubleshooting it with Benjie it seems the issue was caused by your requires being in your function, so we moved them out and everything seems to be working.

### CODE REVIEW

**Comment by benjie** [comment]
(I believe that the issue was that there was still code running after the test, and jest had torn down require by then. This fix at least suppresses the warnings/errors and seems to do no harm.)

**Comment by PaulMcMillan** [comment]
It would be fantastic to see this merged so we don't need to keep carrying an internal fork of this to keep our tests passing.

**Comment by mattbretl** [comment]
Merged, and I'll fix the lint error in a separate PR. Thanks @sk3tch!

**Comment by mattbretl** [comment]
Released v1.0.1 with this fix.

**Pull request merged**
