### PR TITLE
Use lodash.isEqual

### PR DESCRIPTION
**Pull request by singingwolfboy**

### CODE REVIEW

**Comment by benjie** [comment]
I don't think this is worth using a dependency for. If necessary refactor so you define an `isEqual` function up top to be shared, but this doesn't even fall foul of the three-strikes rule.

**Comment by singingwolfboy** [comment]
`lodash` is already a dependency for `graphile-build` and `graphile-build-pg`, and realistically, you can't use this project without also using those libraries. As a result, I'm not actually _adding_ a new dependency here, but using a library that will already be installed (and marking it as a dependency for proper book-keeping).

In addition, `isEqual()` is much clearer to read than trying to understand the intent of the code it is replacing, and this opens up the opportunity to use more lodash functions in this project. I am adding a third usage of `isEqual()` in #19, and there may be more usages in the future.

**Comment by benjie** [comment]
> `lodash` is already a dependency for `graphile-build` and `graphile-build-pg`

`lodash` is _currently_ a dependency for those libraries. I was aware of this (particularly aware because I'm planning to remove it and some other dependencies) when I made the comment :)

If it's being used in multiple places I encourage the refactor to using a shared utility, but I'd be hesitant to use one from a large library like lodash when you only need this one function.

**Comment by singingwolfboy** [comment]
> I'm planning to remove it and some other dependencies

Ah, good to know! In that case, you're right that it's not worth adding this. I'll just define a top-level `isEqual` function, instead.

**Comment by singingwolfboy** [comment]
Closing in favor of #33.

**Pull request closed without merging**
